export const fetchQuote = async () => {
    try {
        const quotes = [
            { "text": "Freedom is a boon, which everyone has the right to receive.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Never bend your head, always hold it high.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Do not think of the enemy as weak, but do not also overestimate their strength.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A person who is brave does not need weapons, but a coward cannot fight even with thousands of weapons.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "The strong are not those who defeat others, but those who defeat their own fears.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "It is not just the sword, but also the mind that wins battles.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Self-confidence and hard work will always earn you success.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Even if there are a thousand enemies, face them like a lion.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A king is a servant first, ruler later.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Victory is achieved by courage and patience, not by mere numbers.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A wise ruler should build a fortress in the hearts of his people.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A warrior does not leave his battlefield, nor does he surrender.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Dharma is greater than wealth, for wealth can be lost, but dharma is eternal.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Justice and honesty are the true marks of a great ruler.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A kingdom built on trust and righteousness will always prosper.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A nation’s strength lies in its unity, not in its wealth.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Power should be used for protection, not oppression.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "One who stands for justice will always find support.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Even the smallest army can achieve greatness with strategy and courage.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Do not fear difficulties; they make you stronger.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A ruler is not above the people; he is their servant.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Knowledge and wisdom are greater than wealth and power.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Defeat is not falling down, but refusing to rise again.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Courage is not the absence of fear, but the ability to act despite it.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A true warrior fights not for personal gain but for his people.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Respect for women is the foundation of a just society.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A nation’s greatness is measured by how it treats its weakest.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Never compromise on your principles, even in the face of adversity.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "He who has self-respect will never bow down to injustice.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A great leader leads by example, not by force.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Hard work, discipline, and courage will lead to success.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A ruler’s duty is to protect the weak and uphold justice.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "True bravery is in standing up for what is right.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Be prepared always, for opportunity comes to those who are ready.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A kingdom that protects its people is a kingdom that lasts.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A good leader does not create followers, but more leaders.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Do not rely on fate; create your own destiny.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "A warrior’s honor is greater than his life.", "author": "Chhatrapati Shivaji Maharaj" },
            { "text": "Be the change that you wish to see in the world.", "author": "Mahatma Gandhi" },
            { "text": "A man is but the product of his thoughts. What he thinks, he becomes.", "author": "Mahatma Gandhi" },
            { "text": "Dream, dream, dream. Dreams transform into thoughts and thoughts result in action.", "author": "Dr. A.P.J. Abdul Kalam" },
            { "text": "Difficulties in your life do not come to destroy you, but to help you realize your hidden potential.", "author": "Dr. A.P.J. Abdul Kalam" },
            { "text": "You cannot believe in God until you believe in yourself.", "author": "Swami Vivekananda" },
            { "text": "Arise, awake, and stop not till the goal is reached.", "author": "Swami Vivekananda" },
            { "text": "All power is within you; you can do anything and everything.", "author": "Swami Vivekananda" },
            { "text": "The greatest religion is to be true to your own nature. Have faith in yourself.", "author": "Swami Vivekananda" },
            { "text": "Patience, persistence, and perspiration make an unbeatable combination for success.", "author": "Napoleon Hill" },
            { "text": "If you fail, never give up because FAIL means First Attempt In Learning.", "author": "Dr. A.P.J. Abdul Kalam" },
            { "text": "A leader should know how to manage failure.", "author": "Dr. A.P.J. Abdul Kalam" },
            { "text": "It is very easy to defeat someone, but it is very hard to win someone.", "author": "Dr. A.P.J. Abdul Kalam" },
            { "text": "Silence is the best answer to someone who doesn’t value your words.", "author": "Dr. A.P.J. Abdul Kalam" },
            { "text": "Luxury and lies have huge maintenance costs. But truth and simplicity are self-maintained.", "author": "Dr. A.P.J. Abdul Kalam" },
            { "text": "Don’t take rest after your first victory because if you fail in second, more lips are waiting to say that your first victory was just luck.", "author": "Dr. A.P.J. Abdul Kalam" },
            { "text": "Happiness is when what you think, what you say, and what you do are in harmony.", "author": "Mahatma Gandhi" },
            { "text": "Live as if you were to die tomorrow. Learn as if you were to live forever.", "author": "Mahatma Gandhi" },
            { "text": "An eye for an eye will only make the whole world blind.", "author": "Mahatma Gandhi" },
            { "text": "Strength does not come from physical capacity. It comes from an indomitable will.", "author": "Mahatma Gandhi" },
            { "text": "You may never know what results come of your actions. But if you do nothing, there will be no result.", "author": "Mahatma Gandhi" },
            { "text": "Knowledge is the only instrument of production that is not subject to diminishing returns.", "author": "J.R.D. Tata" },
            { "text": "If you want to walk fast, walk alone. But if you want to walk far, walk together.", "author": "Ratan Tata" },
            { "text": "None can destroy iron, but its own rust can! Likewise, none can destroy a person, but his own mindset can.", "author": "Ratan Tata" },
            { "text": "Take the stones people throw at you, and use them to build a monument.", "author": "Ratan Tata" },
            { "text": "Your work is to discover your world and then with all your heart give yourself to it.", "author": "Buddha" },
            { "text": "Don’t let the past steal your present.", "author": "Chinmayananda Saraswati" },
            { "text": "The greatest wealth is health.", "author": "Virgil" },
            { "text": "A wise man can learn more from a foolish question than a fool can learn from a wise answer.", "author": "Bruce Lee" },
            { "text": "A person should not be too honest. Straight trees are cut first, and honest people are screwed first.", "author": "Chanakya" },
            { "text": "Before you start some work, always ask yourself three questions: Why am I doing it, What the results might be, and Will I be successful?", "author": "Chanakya" },
            { "text": "As soon as the fear approaches near, attack and destroy it.", "author": "Chanakya" },
            { "text": "The fragrance of flowers spreads only in the direction of the wind. But the goodness of a person spreads in all directions.", "author": "Chanakya" },
            { "text": "Success is not about how much money you make, it's about the difference you make in people's lives.", "author": "Narayana Murthy" },
            { "text": "Change is the law of the universe. You can be a millionaire or a pauper in an instant.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "You have the right to perform your duty, but never to the fruits of your work.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "For one who has conquered his mind, the mind is his best friend. But for one who has failed to do so, his very mind will be his greatest enemy.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "A person can rise through the efforts of his own mind; or in the same manner, draw himself down.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "A person is made by his belief. As he believes, so he becomes.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "He who has no attachments can really love others, for his love is pure and divine.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "Happiness comes not by desire but by detachment.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "Perform your duty and leave the rest to me.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "Man is made by his belief. As he believes, so he is.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "In battle, there is no sin. The righteous fight must be fought.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "A person’s honor is his greatest wealth.", "author": "Lord Rama (Ramayana)" },
            { "text": "The strength of a person is his character and his word.", "author": "Lord Rama (Ramayana)" },
            { "text": "A righteous man never swerves from the path of dharma.", "author": "Lord Rama (Ramayana)" },
            { "text": "One who controls his anger can achieve anything.", "author": "Lord Rama (Ramayana)" },
            { "text": "There is no greater virtue than truth.", "author": "Lord Rama (Ramayana)" },
            { "text": "A person’s greatest wealth is his character, not his riches.", "author": "Lord Rama (Ramayana)" },
            { "text": "It is easy to fight the external enemy, but the real battle is within yourself.", "author": "Lord Rama (Ramayana)" },
            { "text": "Truth and righteousness always prevail.", "author": "Lord Rama (Ramayana)" },
            { "text": "A man is known by his deeds, not his birth.", "author": "Lord Rama (Ramayana)" },
            { "text": "There is no enemy greater than one’s own uncontrolled mind.", "author": "Lord Rama (Ramayana)" },
            { "text": "A promise must always be fulfilled, no matter how difficult.", "author": "Lord Rama (Ramayana)" },
            { "text": "A person’s true nature is revealed in adversity.", "author": "Bhishma (Mahabharata)" },
            { "text": "He who seeks revenge digs two graves—one for himself.", "author": "Bhishma (Mahabharata)" },
            { "text": "Dharma is eternal; everything else is temporary.", "author": "Bhishma (Mahabharata)" },
            { "text": "A true warrior never gives up, no matter how difficult the battle.", "author": "Bhishma (Mahabharata)" },
            { "text": "The greatest victory is victory over oneself.", "author": "Bhishma (Mahabharata)" },
            { "text": "A man’s actions determine his destiny, not his birth.", "author": "Karna (Mahabharata)" },
            { "text": "The best way to defeat an enemy is with kindness.", "author": "Karna (Mahabharata)" },
            { "text": "Loyalty to one’s friends is the greatest virtue.", "author": "Karna (Mahabharata)" },
            { "text": "A person’s greatness is measured by how he treats those beneath him.", "author": "Karna (Mahabharata)" },
            { "text": "True honor is not in victory but in how you fight.", "author": "Karna (Mahabharata)" },
            { "text": "A king is known by how he treats his people.", "author": "Yudhishthira (Mahabharata)" },
            { "text": "Greed destroys even the greatest of men.", "author": "Yudhishthira (Mahabharata)" },
            { "text": "A righteous man never strays from the path of truth.", "author": "Yudhishthira (Mahabharata)" },
            { "text": "The greatest wealth is contentment.", "author": "Yudhishthira (Mahabharata)" },
            { "text": "A man is made by his beliefs. As he believes, so he becomes.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "You have the right to perform your duty, but never to the fruits of your work.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "Change is the law of the universe. You can be a king or a beggar in an instant.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "Perform your duty without attachment to the outcome.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "A person who is not disturbed by happiness and distress and is steady in both is certainly eligible for liberation.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "The mind acts like an enemy for those who do not control it.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "The soul is neither born, nor does it ever die; it is eternal and indestructible.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "He who has no attachments can really love others, for his love is pure and divine.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "Doubt is a great enemy of wisdom. A person who doubts himself cannot achieve success.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "One who sees inaction in action and action in inaction is truly wise.", "author": "Lord Krishna (Bhagavad Gita)" },
            { "text": "A person’s honor is his greatest wealth.", "author": "Lord Rama (Ramayana)" },
            { "text": "The path of truth and righteousness always leads to success.", "author": "Lord Rama (Ramayana)" },
            { "text": "There is no greater virtue than truth.", "author": "Lord Rama (Ramayana)" },
            { "text": "A true warrior never fears challenges; he embraces them.", "author": "Lord Rama (Ramayana)" },
            { "text": "A promise once made must always be fulfilled.", "author": "Lord Rama (Ramayana)" },
            { "text": "Even in the most difficult times, a righteous person never abandons his principles.", "author": "Lord Rama (Ramayana)" },
            { "text": "One should always stand up for justice, even if it means standing alone.", "author": "Lord Rama (Ramayana)" },
            { "text": "It is easy to fight an external enemy, but the real battle is within oneself.", "author": "Lord Rama (Ramayana)" },
            { "text": "A king is not known by his wealth but by his deeds.", "author": "Lord Rama (Ramayana)" },
            { "text": "Forgiveness is the greatest virtue a person can possess.", "author": "Lord Rama (Ramayana)" },
            { "text": "A person’s true nature is revealed in adversity.", "author": "Bhishma (Mahabharata)" },
            { "text": "Dharma is eternal; everything else is temporary.", "author": "Bhishma (Mahabharata)" },
            { "text": "A warrior must fight for justice, not for personal gain.", "author": "Bhishma (Mahabharata)" },
            { "text": "A king who cannot protect his people has no right to rule.", "author": "Bhishma (Mahabharata)" },
            { "text": "A person’s greatness is measured by how he treats those beneath him.", "author": "Bhishma (Mahabharata)" },
            { "text": "The greatest warrior is one who can control his own mind.", "author": "Bhishma (Mahabharata)" },
            { "text": "A true leader never abandons his duty, no matter how difficult the situation.", "author": "Bhishma (Mahabharata)" },
            { "text": "Greed is the root of all suffering.", "author": "Bhishma (Mahabharata)" },
            { "text": "Victory is determined by the righteousness of one's actions.", "author": "Bhishma (Mahabharata)" },
            { "text": "Even the mightiest fall if they abandon dharma.", "author": "Bhishma (Mahabharata)" },
            { "text": "A warrior does not complain about his circumstances, he creates his own destiny.", "author": "Karna (Mahabharata)" },
            { "text": "Loyalty to one’s friends is the greatest virtue.", "author": "Karna (Mahabharata)" },
            { "text": "True honor is not in victory, but in how you fight.", "author": "Karna (Mahabharata)" },
            { "text": "A person’s actions define him, not his birth.", "author": "Karna (Mahabharata)" },
            { "text": "A man without self-control is like a ship without a rudder.", "author": "Yudhishthira (Mahabharata)" },
            { "text": "A king is not known by his crown but by his conduct.", "author": "Yudhishthira (Mahabharata)" },
            { "text": "One’s greatest enemy is not the external world but his own desires.", "author": "Yudhishthira (Mahabharata)" },
            { "text": "The greatest wealth is contentment.", "author": "Yudhishthira (Mahabharata)" },
            { "text": "Shiva is the beginning, the middle, and the end. He is the source of all knowledge and wisdom.", "author": "Lord Shiva" },
            { "text": "When you focus on your work with full dedication, you will achieve everything.", "author": "Lord Shiva" },
            { "text": "The mind is everything. Control your mind, and you control your destiny.", "author": "Lord Shiva" },
            { "text": "Desires lead to attachment, and attachment leads to suffering. Free yourself from both.", "author": "Lord Shiva" },
            { "text": "Nothing is more powerful than self-control. A man who controls himself conquers the world.", "author": "Lord Shiva" },
            { "text": "The greatest virtue is patience, and the greatest strength is forgiveness.", "author": "Lord Shiva" },
            { "text": "Let go of ego, surrender to truth, and you will find liberation.", "author": "Lord Shiva" },
            { "text": "Destruction is necessary for creation. Only through change can growth happen.", "author": "Lord Shiva" },
            { "text": "Meditation and devotion lead to self-realization.", "author": "Lord Shiva" },
            { "text": "Your soul is immortal. Do not fear death, for it is only a transition.", "author": "Lord Shiva" },
            { "text": "A devotee who surrenders to Lord Rama with true faith will always find protection.", "author": "Lord Hanuman" },
            { "text": "Strength is not in the body but in faith and devotion.", "author": "Lord Hanuman" },
            { "text": "Fear has no place in the heart that is filled with devotion.", "author": "Lord Hanuman" },
            { "text": "The path of service is the greatest path to God.", "author": "Lord Hanuman" },
            { "text": "Victory belongs to those who are fearless and righteous.", "author": "Lord Hanuman" },
            { "text": "No evil can touch the one who chants the name of Lord Rama.", "author": "Lord Hanuman" },
            { "text": "Dedication, devotion, and discipline are the pillars of strength.", "author": "Lord Hanuman" },
            { "text": "Humility is the greatest strength. A true servant of God is stronger than any king.", "author": "Lord Hanuman" },
            { "text": "Loyalty to dharma is the highest virtue.", "author": "Lord Hanuman" },
            { "text": "Never doubt your abilities. With faith, nothing is impossible.", "author": "Lord Hanuman" },
            { "text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt" },
            { "text": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt" },
            { "text": "The best way to predict the future is to create it.", "author": "Peter Drucker" },
            { "text": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt" },
            { "text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs" },
            { "text": "Success is not the key to happiness. Happiness is the key to success.", "author": "Albert Schweitzer" },
            { "text": "Opportunities don't happen, you create them.", "author": "Chris Grosser" },
            { "text": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis" },
            { "text": "Happiness depends upon ourselves.", "author": "Aristotle" },
            { "text": "Success is how high you bounce when you hit bottom.", "author": "George S. Patton" },
            { "text": "Your limitation—it’s only your imagination.", "author": "Unknown" },
            { "text": "Push yourself, because no one else is going to do it for you.", "author": "Unknown" },
            { "text": "Sometimes later becomes never. Do it now.", "author": "Unknown" },
            { "text": "Great things never come from comfort zones.", "author": "Unknown" },
            { "text": "Dream it. Wish it. Do it.", "author": "Unknown" },
            { "text": "Stay hungry. Stay foolish.", "author": "Steve Jobs" },
            { "text": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis" },
            { "text": "Everything you’ve ever wanted is on the other side of fear.", "author": "George Addair" },
            { "text": "Don’t watch the clock; do what it does. Keep going.", "author": "Sam Levenson" },
            { "text": "A problem is a chance for you to do your best.", "author": "Duke Ellington" },
            { "text": "Happiness is not something ready made. It comes from your own actions.", "author": "Dalai Lama" },
            { "text": "Perfection is not attainable, but if we chase perfection we can catch excellence.", "author": "Vince Lombardi" },
            { "text": "The secret of getting ahead is getting started.", "author": "Mark Twain" },
            { "text": "Keep going. Everything you need will come to you at the perfect time.", "author": "Unknown" },
            { "text": "The harder the battle, the sweeter the victory.", "author": "Les Brown" },
            { "text": "Don’t stop when you’re tired. Stop when you’re done.", "author": "Unknown" },
            { "text": "Little by little, one travels far.", "author": "J.R.R. Tolkien" },
            { "text": "It always seems impossible until it’s done.", "author": "Nelson Mandela" },
            { "text": "If you want to achieve greatness stop asking for permission.", "author": "Unknown" },
            { "text": "The road to success and the road to failure are almost exactly the same.", "author": "Colin R. Davis" },
            { "text": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau" },
            { "text": "Don’t be afraid to give up the good to go for the great.", "author": "John D. Rockefeller" },
            { "text": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson" },
            { "text": "Success is not in what you have, but who you are.", "author": "Bo Bennett" },
            { "text": "Failure will never overtake me if my determination to succeed is strong enough.", "author": "Og Mandino" },
            { "text": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt" },
            { "text": "A journey of a thousand miles begins with a single step.", "author": "Lao Tzu" },
            { "text": "The best revenge is massive success.", "author": "Frank Sinatra" },
            { "text": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Zig Ziglar" },
            { "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs" },
            { "text": "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", "author": "James Cameron" },
            { "text": "Quality means doing it right when no one is looking.", "author": "Henry Ford" },
            { "text": "Don’t cry because it’s over, smile because it happened.", "author": "Dr. Seuss" },
            { "text": "Difficulties in life are intended to make us better, not bitter.", "author": "Dan Reeves" },
            { "text": "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", "author": "Colin Powell" },
            { "text": "Do what you feel in your heart to be right – for you’ll be criticized anyway.", "author": "Eleanor Roosevelt" },
            { "text": "If life were predictable it would cease to be life, and be without flavor.", "author": "Eleanor Roosevelt" },
            { "text": "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", "author": "Buddha" },
            { "text": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson" },
            { "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs" },
            { "text": "It is not length of life, but depth of life.", "author": "Ralph Waldo Emerson" },
            { "text": "Do what you love, and you will never work a day in your life.", "author": "Confucius" },
            { "text": "Happiness is not something ready made. It comes from your own actions.", "author": "Dalai Lama" },
            { "text": "If opportunity doesn’t knock, build a door.", "author": "Milton Berle" },
            { "text": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau" },
            { "text": "What we achieve inwardly will change outer reality.", "author": "Plutarch" },
            { "text": "Challenges are what make life interesting and overcoming them is what makes life meaningful.", "author": "Joshua J. Marine" },
            { "text": "Strive not to be a success, but rather to be of value.", "author": "Albert Einstein" },
            { "text": "You don’t have to be great to start, but you have to start to be great.", "author": "Zig Ziglar" },
            { "text": "Act as if what you do makes a difference. It does.", "author": "William James" },
            { "text": "Courage is resistance to fear, mastery of fear—not absence of fear.", "author": "Mark Twain" },
            { "text": "The mind is everything. What you think you become.", "author": "Buddha" },
            { "text": "A person who never made a mistake never tried anything new.", "author": "Albert Einstein" },
            { "text": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky" },
            { "text": "The best preparation for tomorrow is doing your best today.", "author": "H. Jackson Brown, Jr." },
            { "text": "The only place where success comes before work is in the dictionary.", "author": "Vidal Sassoon" },
            { "text": "All our dreams can come true if we have the courage to pursue them.", "author": "Walt Disney" },
            { "text": "Don’t watch the clock; do what it does. Keep going.", "author": "Sam Levenson" },
            { "text": "If you set your goals ridiculously high and it’s a failure, you will fail above everyone else’s success.", "author": "James Cameron" },
            { "text": "Failure is not the opposite of success; it’s part of success.", "author": "Arianna Huffington" },
            { "text": "Act as if it were impossible to fail.", "author": "Dorothea Brande" },
            { "text": "The best time to plant a tree was 20 years ago. The second-best time is now.", "author": "Chinese Proverb" },
            { "text": "Opportunities multiply as they are seized.", "author": "Sun Tzu" },
            { "text": "You are confined only by the walls you build yourself.", "author": "Andrew Murphy" },
            { "text": "The key to success is to start before you are ready.", "author": "Marie Forleo" },
            { "text": "You can’t cross the sea merely by standing and staring at the water.", "author": "Rabindranath Tagore" },
            { "text": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill" },
            { "text": "There are two ways of spreading light: to be the candle or the mirror that reflects it.", "author": "Edith Wharton" },
            { "text": "Everything you can imagine is real.", "author": "Pablo Picasso" },
            { "text": "Don’t let what you cannot do interfere with what you can do.", "author": "John Wooden" },
            { "text": "Life isn’t about finding yourself. It’s about creating yourself.", "author": "George Bernard Shaw" },
            { "text": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela" },
            { "text": "Happiness depends upon ourselves.", "author": "Aristotle" },
            { "text": "We may encounter many defeats but we must not be defeated.", "author": "Maya Angelou" },
            { "text": "Work hard in silence, let your success be your noise.", "author": "Frank Ocean" },
            { "text": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson" },
            { "text": "Life is what happens when you're busy making other plans.", "author": "John Lennon" },
            { "text": "If you want to live a happy life, tie it to a goal, not to people or things.", "author": "Albert Einstein" },
            { "text": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius" },
            { "text": "Courage is grace under pressure.", "author": "Ernest Hemingway" },
            { "text": "An unexamined life is not worth living.", "author": "Socrates" },
            { "text": "Happiness is not something ready made. It comes from your own actions.", "author": "Dalai Lama" },
            { "text": "The only thing necessary for the triumph of evil is for good men to do nothing.", "author": "Edmund Burke" },
            { "text": "The weak can never forgive. Forgiveness is the attribute of the strong.", "author": "Mahatma Gandhi" },
            { "text": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi" },
            { "text": "Happiness depends upon ourselves.", "author": "Aristotle" },
            { "text": "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "author": "Aristotle" },
            { "text": "The best way to find yourself is to lose yourself in the service of others.", "author": "Mahatma Gandhi" },
            { "text": "It is never too late to be what you might have been.", "author": "George Eliot" },
            { "text": "If you tell the truth, you don't have to remember anything.", "author": "Mark Twain" },
            { "text": "Strive not to be a success, but rather to be of value.", "author": "Albert Einstein" },
            { "text": "The most difficult thing is the decision to act, the rest is merely tenacity.", "author": "Amelia Earhart" },
            { "text": "Do what you feel in your heart to be right—for you’ll be criticized anyway.", "author": "Eleanor Roosevelt" },
            { "text": "Keep your face always toward the sunshine—and shadows will fall behind you.", "author": "Walt Whitman" },
            { "text": "The best and most beautiful things in the world cannot be seen or even touched—they must be felt with the heart.", "author": "Helen Keller" },
            { "text": "Live as if you were to die tomorrow. Learn as if you were to live forever.", "author": "Mahatma Gandhi" },
            { "text": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett" },
            { "text": "Don’t let yesterday take up too much of today.", "author": "Will Rogers" },
            { "text": "Don’t wait. The time will never be just right.", "author": "Napoleon Hill" },
            { "text": "Life is either a daring adventure or nothing at all.", "author": "Helen Keller" },
            { "text": "Don’t count the days, make the days count.", "author": "Muhammad Ali" },
            { "text": "If you can dream it, you can achieve it.", "author": "Zig Ziglar" },
            { "text": "Doubt kills more dreams than failure ever will.", "author": "Suzy Kassem" },
            { "text": "You only live once, but if you do it right, once is enough.", "author": "Mae West" },
            { "text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney" },
            { "text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs" },
            { "text": "Everything you’ve ever wanted is on the other side of fear.", "author": "George Addair" },
            { "text": "Don’t wish it were easier. Wish you were better.", "author": "Jim Rohn" },
            { "text": "In the middle of every difficulty lies opportunity.", "author": "Albert Einstein" },
            { "text": "What we achieve inwardly will change outer reality.", "author": "Plutarch" },
            { "text": "Work hard in silence, let your success be your noise.", "author": "Frank Ocean" },
            { "text": "A man who stands for nothing will fall for anything.", "author": "Malcolm X" },
            { "text": "Efforts and courage are not enough without purpose and direction.", "author": "John F. Kennedy" },
            { "text": "Success is getting what you want. Happiness is wanting what you get.", "author": "Dale Carnegie" },
            { "text": "The only true wisdom is in knowing you know nothing.", "author": "Socrates" },
            { "text": "Education is the most powerful weapon which you can use to change the world.", "author": "Nelson Mandela" },
            { "text": "The purpose of our lives is to be happy.", "author": "Dalai Lama" },
            { "text": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt" },
            { "text": "Live as if you were to die tomorrow. Learn as if you were to live forever.", "author": "Mahatma Gandhi" },
            { "text": "If you look at what you have in life, you’ll always have more.", "author": "Oprah Winfrey" },
            { "text": "Success is not the key to happiness. Happiness is the key to success.", "author": "Albert Schweitzer" },
            { "text": "Opportunities don’t happen. You create them.", "author": "Chris Grosser" },
            { "text": "The only place where success comes before work is in the dictionary.", "author": "Vidal Sassoon" },
            { "text": "Act as if what you do makes a difference. It does.", "author": "William James" },
            { "text": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius" },
            { "text": "Perseverance is not a long race; it is many short races one after the other.", "author": "Walter Elliot" },
            { "text": "A person who never made a mistake never tried anything new.", "author": "Albert Einstein" },
            { "text": "Do what you feel in your heart to be right – for you’ll be criticized anyway.", "author": "Eleanor Roosevelt" },
            { "text": "Difficulties in life are intended to make us better, not bitter.", "author": "Dan Reeves" },
            { "text": "You must expect great things of yourself before you can do them.", "author": "Michael Jordan" },
            { "text": "It’s not whether you get knocked down, it’s whether you get up.", "author": "Vince Lombardi" },
            { "text": "Life isn’t about getting and having, it’s about giving and being.", "author": "Kevin Kruse" },
            { "text": "The only way to do great work is to love what you do.", "author": "Steve Jobs" },
            { "text": "The harder the conflict, the greater the triumph.", "author": "George Washington" },
            { "text": "We may encounter many defeats but we must not be defeated.", "author": "Maya Angelou" },
            { "text": "Work hard in silence, let success make the noise.", "author": "Frank Ocean" },
            { "text": "The best revenge is massive success.", "author": "Frank Sinatra" },
            { "text": "Change your thoughts and you change your world.", "author": "Norman Vincent Peale" },
            { "text": "The man who has confidence in himself gains the confidence of others.", "author": "Hasidic Proverb" },
            { "text": "The only thing standing between you and your goal is the story you keep telling yourself.", "author": "Jordan Belfort" },
            { "text": "Success is not in what you have, but who you are.", "author": "Bo Bennett" },
            { "text": "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", "author": "Roy T. Bennett" },
            { "text": "A goal is not always meant to be reached; it often serves simply as something to aim at.", "author": "Bruce Lee" },
            { "text": "Don’t wish it were easier. Wish you were better.", "author": "Jim Rohn" },
            { "text": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky" },
            { "text": "Great things never come from comfort zones.", "author": "Unknown" },
            { "text": "Push yourself, because no one else is going to do it for you.", "author": "Unknown" },
            { "text": "Stay hungry. Stay foolish.", "author": "Steve Jobs" },
            { "text": "Life is what happens when you're busy making other plans.", "author": "John Lennon" },
            { "text": "Doubt kills more dreams than failure ever will.", "author": "Suzy Kassem" },
            { "text": "The best time to plant a tree was 20 years ago. The second-best time is now.", "author": "Chinese Proverb" }


        ];

        const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
        return { text: randomQuote.text, author: randomQuote.author };
    } catch (error) {
        console.error("Error fetching quote:", error.message);
        return { text: "⚠️ Failed to load quote. Try again.", author: "Het Dabhi" };
    }
};
